routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\OrderDetailController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\SANPHAMController;
use Illuminate\Support\Facades\Auth;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('lang/{locale}', function ($locale) {
    if (!in_array($locale, ['en', 'vi'])) {
        abort(404);
    }
    session()->put('locale', $locale);
    return redirect()->back();
});

Route::get('/login', function () {
    return view('auth.login');
})->name('login');

Route::post('/login', [\App\Http\Controllers\Auth\LoginController::class, 'login'])->name('auth.login');


Route::middleware(['auth'])->group(function() {
    Route::group(['middleware'=> 'checkRole:admin'],function(){
        Route::get('/', function () {
            return view('dashboard');
        });
        Route::resource('order', OrderController::class);
        Route::get('/logout', [\App\Http\Controllers\Auth\LoginController::class, 'logout'])->name('auth.logout');
        Route::delete('/delete/{id}', [ProductController::class, 'destroy']);
        Route::resource('user', UserController::class);
        Route::get('/user/export/', 'UserController@export');
    });
    Route::group(['middleware'=> 'checkRole:manager'],function(){
        Route::resource('product', ProductController::class);
        Route::resource('SANPHAM', SANPHAMController::class);
    });
});
Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;
    protected $connection = 'mysql';
    protected $table = 'products';

    public function details() {
        return $this->hasMany(ProductDetail::class, 'product_id', 'id');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Models\Categories;
use App\Models\ProductDetail;
use Illuminate\Http\Request;
use App\Models\Product;
use App\Models\Size;
use Illuminate\Support\Facades\DB;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::paginate(10);
        $data['products'] = $products;
        return view('product/list')->with($data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Categories::all();
        $sizes = Size::all();
        $data['categories'] = $categories;
        $data['sizes'] = $sizes;
        return view('product/create')->with($data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
//        dd($request);
        try {
            DB::beginTransaction();
            $this->validate(request(), [
                'name' => 'required',
                'price.*' => 'required|numeric',
                'img' => 'required',
            ]);
            $product = new Product();
            $product->name = $request->name;
            $product->cate_id = $request->category;
            $product->img = $request->image;
            $product->save();
            $product_id = Product::select('id')->limit(1)->orderby('id', 'DESC')->get();
            for ($i = 0; $i < count($request->size); $i++) {
                $price = str_replace(".", "", $request->price[$i]);
                $dataInsert = [
                    'product_id' => $product_id[0]->id,
                    'size_id' => $request->size[$i],
                    'price' => $price
                ];
                $dataInserts[$i] = $dataInsert;
            }
            ProductDetail::insert($dataInserts);

            $product = Product::find($product_id[0]->id);
            $sizes = Size::all();
            $data['product'] = $product;
            $data['sizes'] = $sizes;
            DB::commit();
            return view('product.detail')->with($data);
        }
        catch (Exception $e){
            DB::rollBack();
            return redirect()->back()->withErrors($e->getMessage());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $product = Product::find($id);
        $sizes = Size::all();
        $data['product'] = $product;
        $data['sizes'] = $sizes;
        return view('product.detail')->with($data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Product::find($id);
        $data['product'] = $product;
        return view('product/edit')->with($data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try {
            DB::beginTransaction();
            $product = Product::find($id);
            if (!$product) {
                abort(404);
            }
            $product->name = $request->name_product;
            $product->save();
            ProductDetail::where("product_id", $product->id)->delete();
            for ($i = 0; $i < count($request->size); $i++) {
                $price = str_replace(".", "", $request->price[$i]);
                $dataInsert = [
                    'product_id' => $product->id,
                    'size_id' => $request->size[$i],
                    'price' => $price
                ];
                $dataInserts[$i] = $dataInsert;
            }
            ProductDetail::insert($dataInserts);
            DB::commit();
        } catch (Exception $e) {
            DB::rollBack();
            return redirect()->back()->withErrors($e->getMessage());
        }
        return redirect()->back()->with(['success' => 'Data update successful!']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            DB::beginTransaction();
            $product_id = ProductDetail::find($id)->select('product_id')->get();
            ProductDetail::find($id)->delete();
            if(count($product_id) == 0){
                Product::find($product_id)->delete();
            }
            DB::commit();
        }
        catch (Exception $e){
            DB::rollBack();
            return response()->json(['error'=>true]);
        }
        return response()->json(['error'=>false]);
    }
}

resources/views/Product/create.blade.php
@extends('layouts.main')
@section('content')
    @if (session()->has('message'))
        <div class="alert alert-success">
            {{ session()->get('message') }}
        </div>
    @endif
    @if ($errors->any())
        <div class="alert">
            <ul class="list-group">
                @foreach($errors->all() as $error)
                    <li class="list-group-item">
                        {{ $error }}
                    </li>
                @endforeach
            </ul>
        </div>
    @endif
    <div class="row">
        <div class="col-12">
            <div class="card card-secondary">
                <div class="card-header">
                    <h3 class="card-title">Create new product</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                <form method="POST" action="{{ route('product.store') }}">
                    @csrf
                    <div class="card-body">
                        <div class="form-group">
                            <label for="productCode">Product Code</label>
                            <input type="text" value="{{ old('product_code') }}" name="product_cd" class="form-control"
                                   id="productCode" placeholder="Please input product code">
                        </div>
                        <div class="form-group">
                            <label for="name">Product Name</label>
                            <input type="text" value="{{ old('name') }}" class="form-control" id="name"
                                   placeholder="Please input product name">
                        </div>
                        <div class="form-group">
                            <div class="input-group">
                                <span class="input-group-btn">
                                    <a id="lfm" data-input="thumbnail" data-preview="holder" class="btn btn-primary">
                                    <i class="fa fa-picture-o"></i> Choose
                                    </a>
                                </span>
                                <input id="thumbnail" class="form-control" type="text" name="filepath">
                            </div>
                            <img id="holder" style="margin-top:15px;max-height:100px;">
                        </div>
                        <div>
                        </div>
                        <div id="add_item">
                            @php $check = true;
                            @endphp
                            <div class="form-row">
                                <div class="form-group col-md-2">
                                    <label for="size">Size</label>
                                    <select class="form-control" name="size[]">
                                        @foreach($sizes as $size)
                                            <option
                                                value="{{ $size->id }}">{{ $size->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" id="exampleCheck1">
                            <label class="form-check-label" for="exampleCheck1">Check me out</label>
                        </div>
                    </div>
                    <!-- /.card-body -->

                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

@endsection

@push('script')
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="/vendor/laravel-filemanager/js/stand-alone-button.js"></script>
    <script type="text/javascript">
        $('#lfm').filemanager('image');

        $('#thumbnail').change(function(e) {
            $('#holder').attr('src', $(this).val());
        });
        // $('#btn_thumbnail').filemanager('file');
        const max_row = 10;
        const add_item = $("#add_item");

        function click_function() {
            let current_row = $('.form-row').length;
            if (current_row < max_row) {
                add_item.append('<div class="form-row">\n' +
                    '                                    <div class="form-group col-md-2">\n' +
                    '                                        <label for="size">Size</label>\n' +
                    '                                        <select class="form-control" name="size[]">\n' +
                    '                                            @foreach($sizes as $size)\n' +
                    '                                                <option value="{{ $size->id }}" >{{ $size->name }}</option>\n' +
                    '                                            @endforeach\n' +
                    '                                        </select>\n' +
                    '                                    </div>\n' +
                    '                                    <div class="form-group col-md-2">\n' +
                    '                                        <label for="price">Price</label>\n' +
                    '                                        <input type="text" class="form-control price" name="price[]" value="0" />\n' +
                    '                                    </div>\n' +
                    '                                    <div class="form-group col-md-1 d-flex align-items-end btn_deletes">\n' +
                    '                                        <button type="button" class="btn_delete btn btn-danger btn-outline js-addSize" style="display: block;height: 40px;"><i class="fa fa-minus"></i></button>\n' +
                    '                                    </div>\n' +
                    '                                </div>');
                $(".btn_delete").click(function () {
                    if ($('.form-row').length > 1) {
                        $(this).closest('.form-row').remove();
                    }
                })
            }
        }

        $(document).ready(function () {
            $(".btn_delete").click(function () {
                if ($('.form-row').length > 1) {
                    $(this).closest('.form-row').remove();
                }
            })
        })

        function remove_function() {
            $(".price").attr('value', '');
            $('#productname').attr('value', '');
        }

    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
@endpush

resources/views/Product/detail.blade.php
@extends('layouts.main')
@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Product #{{ $product->id }}-{{ $product->name }}</h3>
                    </div>
                    <div class="card-body">
                    <form method="POST" action="{{ route('product.update', $product) }}">
                        @csrf()
                        @method('PUT')
                            <div class="form-group">
                                <label for="productname">Product name</label>
                                <input type="text" class="form-control" name="name" id="productname" value="{{ $product->name }}" />
                            </div>
                            <div id="add_item">
                            @php $check = true; @endphp
                            @foreach($product->details as $detail)
                            <div class="form-row">
                                <div class="form-group col-md-2">
                                    <label for="size">Size</label>
                                    <select class="form-control" name="size[]">
                                        @foreach($sizes as $size)
                                            <option value="{{ $size->id }}" {{ $detail->size_id == $size->id ? "selected" : "" }}>{{ $size->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                                <div class="form-group col-md-2">
                                    <label for="price">Price</label>
                                    <input type="text" class="form-control price" name="price[]" value="{{ number_format($detail->price, 0, ',', '.') }}" />
                                </div>
                                @if ($check)
                                    @php $check = !$check; @endphp
                                <div class="form-group col-md-1 d-flex align-items-end">
                                    <button type="button" class="btn btn-success btn-outline js-addSize" style="display: block;height: 40px;" onclick="click_function()"><i class="fa fa-plus"></i></button>
                                </div>
                                @else
                                <div class="form-group col-md-1 d-flex align-items-end">
                                    <button type="button" class="btn_delete btn btn-danger btn-outline js-addSize" style="display: block;height: 40px;"><i class="fa fa-minus"></i></button>
                                </div>
                                @endif
                            </div>
                            @endforeach
                            </div>
                            <div class="d-flex justify-content-between">
                                <div>
                                    <a class="btn btn-default" href="{{ route('product.index') }}">Back</a>
                                    <button type="button" class="btn btn-default" onclick="reset_function()">Reset</button>
                                </div>
                                <button type="submit" class="btn btn-primary">Save</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('script')
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
        const add_item = $("#add_item");
        const max = 10;
        $(document).ready(function() {
            $(".btn_delete").click(function () {
                if($('.form-row').length > 1) {
                    $(this).closest('.form-row').remove();
                }
                if($(this).closest('.form-row').hasClass('add-button')){
                    console.log("oke")
                }
            })
        })
        function click_function() {
            let current_row = $('.form-row').length;
            if (current_row < max) {
            $('.add-button').remove();
            add_item.append('<div class="form-row">\n' +
                                '<div class="form-group col-md-2">\n' +
                                    '<label for="size">Size</label>\n' +
                                    '<select class="form-control" name="size[]">\n' +
                                        '@foreach($sizes as $size)\n' +
                                            '<option value="{{ $size->id }}" {{ $detail->size_id == $size->id ? "selected" : "" }}>{{ $size->name }}</option>\n' +
                                        '@endforeach\n' +
                                    '</select>\n' +
                                '</div>\n' +
                                '<div class="form-group col-md-2">\n' +
                                    '<label for="price">Price</label>\n' +
                                    '<input type="text" class="form-control price" name="price[]" value="0" />\n' +
                                '</div>\n' +
                                '<div class="form-group col-md-1 d-flex align-items-end">\n' +
                                    '<button type="button" class="btn_delete btn btn-danger btn-outline js-addSize" style="display: block;height: 40px;"><i class="fa fa-minus"></i></button>\n' +
                                '</div>\n' +
                            '</div>\n');
            $(".btn_delete").click(function () {
                if($('.form-row').length > 1) {
                    $(this).closest('.form-row').remove();
                }
            })
        }
        }
        function reset_function() {
           $(".price").attr('value', '0');
           $('#productname').attr('value', '');
        }
    </script>
  @endpush

resources/views/Product/edit.blade.php
@extends('layouts.app')
@if(session()->has('message'))
    <div class="alert alert-success">
        {{ session()->get('message') }}
    </div>
    @endif
        @if($errors->any())
            <div class="alert alert-danger">
                <ul class="list-group">
                    @foreach($errors->all() as $error)
                        <li class="list-group-item">
                            {{ $error }}
                        </li>
                    @endforeach
                </ul>
            </div>
        @endif
<form method="POST" action="{{ route('product.update', $product->id) }}">
    @csrf()
    @method('PUT')
    <div class="form-row">
        <div class="form-group col-md-6">
        <label for="product_code">Product Code</label>
        <input type="text" class="form-control" name="product_code" value="{{ old('product_code') ?? $product->product_code }}">
        </div>
        <div class="form-group col-md-6">
        <label for="name">Name</label>
            <input type="text" class="form-control" name="name" value="{{ old('name') ?? $product->name }}">
        </div>
    </div>
    <div class="form-group col-md-6">
    <label for="description">Description</label>
        <input type="text" class="form-control" name="description" value="{{ old('description') ?? $product->description }}">
    </div><br>
    <div class="form-group col-md-6">
    <label for="description">Price</label>
        <input type="text" class="form-control" name="price" value="{{ old('price') ?? $product->price }}">
    </div><br>
    <div id="hot" class="form-group col-md-6">
            Hot:<br>
            <input type="radio" id="trueHot" name="hot" value="1" {{$product->hot == '1' ? "checked" : "" }}>
            <label for="1">True</label><br>
            <input type="radio" id="falseHot" name="hot" value="0" {{$product->hot == '0' ? "checked" : "" }}>
            <label for="0">False</label><br>
        </div><br>
        <div id="sale" class="form-group col-md-6">
            Sale:<br>
            <input type="radio" id="trueSale" name="sale" value="1" {{$product->sale == '1' ? "checked" : "" }}>
            <label for="1"> True </label><br>
            <input type="radio" id="falseSale" name="sale" value="0" {{$product->sale == '0' ? "checked" : "" }}>
            <label for="0">False</label><br>
        </div>
        <button type="submit">Submit</button>
            <a href="{{ route('products.index') }}">Back</a>
</form>

resources/views/Product/list.blade.php
@extends('layouts.main')
@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Product List</h3>
                    </div>
                    <div class="card-body">
                        <table id="example2" class="table table-bordered table-hover">
                            <thead>
                            <tr>
                                <th>No.</th>
                                <th>Product Name</th>
                                <th>Product Image</th>
                                <th>Price</th>
                                <th>Size</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @php
                                $count = 0;
                            @endphp
                            @foreach ($products as $key => $product)
                                @foreach($product->details as $detail)
                                <tr>
                                    <td>{{++$count}}</td>
                                    <td>{{ $product->name }}</td>
                                    <td>
                                        <img src="/storage/app/public/files/1/{{$product->img}}" height="60" width="60">

                                        <img src="{{asset('storage/'.$product->img.'')}}" height="60" width="60">
                                    </td>
                                    <td>{{ number_format($detail->price, 0, ',', '.') }}</td>
                                    <td>{{ $detail->size->name }}</td>
                                    <td>
                                        <a class="btn btn-success" href="{{ route('product.show', $product) }}" title="Edit"><i class="fa fa-edit"></i></a>
                                        <a class="btn btn-danger " href="#" onclick="deleteProduct({{$detail->id}})" title="Delete"><i class="fa fa-trash"></i></a>
                                    </td>
                                </tr>
                                @endforeach
                            @endforeach
                            </tbody>
                        </table>
                        <div>{{ $products->links() }}</div>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
@endsection
@push('script')
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script type="text/javascript">
        function deleteProduct(id) {
            swal({
                title: "Are you sure?",
                text: "Once deleted, you will not be able to recover this imaginary file!",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            }).then((willDelete) => {
                if (willDelete){
                    $.ajax({
                        url: '/product/' + id,
                        method: 'DELETE',
                        data: {
                            _token: '{{csrf_token()}}'
                        },
                        success: function (result){
                            if (!result.error){
                                swal("Good job!", "Item deleted successfully!","success")
                                    .then((value) => {
                                        location.reload();
                                    });
                                return;
                            }
                            swal("Failed!", "Some error occur, please contact administrator!","error");
                        }
                    })
                }else{ swal("Cancel!"); }
            })
        }
    </script>
@endpush