routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\OrderDetailController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\SANPHAMController;
use Illuminate\Support\Facades\Auth;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('lang/{locale}', function ($locale) {
    if (!in_array($locale, ['en', 'vi'])) {
        abort(404);
    }
    session()->put('locale', $locale);
    return redirect()->back();
});

Route::get('/login', function () {
    return view('auth.login');
})->name('login');

Route::post('/login', [\App\Http\Controllers\Auth\LoginController::class, 'login'])->name('auth.login');


Route::middleware(['auth'])->group(function() {
    Route::group(['middleware'=> 'checkRole:admin'],function(){
        Route::get('/', function () {
            return view('dashboard');
        });
        Route::resource('order', OrderController::class);
        Route::get('/logout', [\App\Http\Controllers\Auth\LoginController::class, 'logout'])->name('auth.logout');
        Route::delete('/delete/{id}', [ProductController::class, 'destroy']);
        Route::resource('user', UserController::class);
        Route::get('/user/export/', 'UserController@export');
    });
    Route::group(['middleware'=> 'checkRole:manager'],function(){
        Route::resource('product', ProductController::class);
        Route::resource('SANPHAM', SANPHAMController::class);
    });
});
Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    protected $connection = 'mysql';
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Mail;
use App\Mail\WelcomeMail;

class UserController extends Controller
{
    public function export()
    {
        return Excel::download(new UsersExport, 'users.xlsx');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::paginate(10);
        $data['users'] = $users;
        return view('user.list')->with($data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {
            DB::beginTransaction();
            $this->validate(request(), [
                'name' => 'required',
                'email' => 'required|email',
                'password' => 'required'
            ]);
            $user = new User();
            $user->name = $request->name;
            $user->email = $request->email;
            $user->password = Hash::make($request->password);
            $user->dob = $request->dob;
            $user->gender = $request->gender;
            $user->role = $request->role;

            if(!$request->hasFile("image")) {
                $user->image = $request->image;
            }else{
                $image= $request->file("image");
                $path = $image->store("images", "public");
                $user->image = $path;
            }

            Mail::to($user->email)->send(new WelcomeMail($user));
            $user->save();
            DB::commit();
            return redirect()->back()->with([
                'success' => 'Create user successfully!'
            ]);
        }
        catch (Exception $e){
            DB::rollBack();
            return redirect()->back()->withErrors($e->getMessage());
        }
     }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::find($id);
        $data['user'] = $user;
        return view('user.detail')->with($data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try {
            DB::beginTransaction();
            $this->validate(request(), [
                'name' => 'required',
                'email' => 'required|email'
            ]);
            $user = User::find($id);
            $user->name = $request->name;
            $user->email = $request->email;
            if($request->password != ""){
                $user->password = Hash::make($request->password);
                dd($user->password);
            }
            $user->dob = $request->dob;
            $user->gender = $request->gender;
            $user->role = $request->role;
            $user->save();
            DB::commit();
            return redirect()->back()->with(['success' => 'Update user successfully!']);
        }
        catch (\Exception $e){
            DB::rollBack();
            return redirect()->back()->withErrors($e->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/User/create.blade.php
@extends('layouts.main')
@section('content')
    <div class="card card-secondary">
        <div class="card-header">
            <h3 class="card-title">Create new user</h3>
        </div>
        @if($errors->any())
            <div class="alert alert-danger">
                <ul class="list-group">
                    @foreach($errors->all() as $error)
                        <li class="list-group-item" style="color:#ec4844">
                            {{ $error }}
                        </li>
                    @endforeach
                </ul>
            </div>
        @endif
        <form method="POST" action="{{route('user.store')}}">
            @csrf
            <div class="card-body">
                <div class="form-group">
                    <label>User name</label>
                    <input type="text" class="form-control" name="name"
                           placeholder="Enter user name">
                </div>
                <div class="form-group">
                    <label>Email</label>
                    <input type="email" class="form-control" name="email" placeholder="Enter email" aria-describedby="emailHelp">
                </div>
                <div class="form-group">
                    <label>Password</label>
                    <input type="text" class="form-control" name="password" placeholder="Enter password">
                </div>
                <div class="form-group">
                    <label>Day of birth</label>
                    <input type="date" class="form-control" name="dob" placeholder="Enter DOB">
                </div>
                <div class="form-group">
                    <label>Gender</label>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="gender" value="1" checked>
                        <label class="form-check-label">
                            Male
                        </label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="gender" value="0">
                        <label class="form-check-label">
                            Female
                        </label>
                    </div>
                </div>
                <div class="form-group">
                    <label>Role</label>
                    <select class="form-control col-md-4" name="role">
                        <option value="admin">Admin</option>
                        <option value="manager">Manager</option>
                        <option value="customer">Customer</option>
                    </select>
                </div>
                <div>
                    <label>Avatar</label>
                <div class="input-group">
                    <span class="input-group-btn">
                        <a id="lfm" data-input="thumbnail" data-preview="holder" class="btn btn-primary">
                        <i class="fa fa-picture-o"></i> Choose
                        </a>
                    </span>
                    <input id="thumbnail" class="form-control" type="text" name="image">
                    </div>
                    <img id="holder" style="margin-top:15px;max-height:100px;">
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </form>
    </div>
@endsection

@push('script')
<script src="/vendor/laravel-filemanager/js/stand-alone-button.js"></script>
<script>
    $('#lfm').filemanager('image');
    var route_prefix = "url-to-filemanager";
    $('#lfm').filemanager('image', {prefix: route_prefix});
</script>
@endpush

resources/views/User/detail.blade.php
@extends('layouts.main')
@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">User #{{ $user->id }}-{{ $user->name }}</h3>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{route('user.update', $user)}}">
                            @csrf
                            @method('PUT')
                            <div class="card-body">
                                <div class="form-group">
                                    <label>User name</label>
                                    <input type="text" class="form-control reset" name="name"
                                           placeholder="Enter user name" value="{{$user->name}}">
                                </div>
                                <div class="form-group">
                                    <label>Email</label>
                                    <input type="email" class="form-control reset" name="email"
                                           placeholder="Enter email"
                                           aria-describedby="emailHelp" value="{{$user->email}}">
                                </div>
                                <div class="form-group">
                                    <label>Password</label>
                                    <input type="password" class="form-control reset" name="password" id="password"
                                           placeholder="Enter password">
                                </div>
                                <div class="form-group">
                                    <label>Confirm password</label>
                                    <input type="password" class="form-control reset" id="cf_password"
                                           onchange="checkpass()"
                                           placeholder="Enter confirm password">
                                    <div id="error_pass"></div>
                                </div>
                                <div class="form-group">
                                    <label>Day of birth</label>
                                    <input type="date" class="form-control reset" name="dob" placeholder="Enter DOB"
                                           value="{{\Carbon\Carbon::parse($user->dob)->format('Y-m-d')}}">
                                </div>
                                <div class="form-group">
                                    <label>Gender</label>
                                    <div class="form-check">
                                        <input class="form-check-input" type="radio" name="gender"
                                               value="1" {{$user->gender = 1 ? 'checked' : ''}} >
                                        <label class="form-check-label">
                                            Male
                                        </label>
                                    </div>
                                    <div class="form-check">
                                        <input class="form-check-input" type="radio" name="gender"
                                               value="0" {{$user->gender = 0 ? 'checked' : ''}}>
                                        <label class="form-check-label">
                                            Female
                                        </label>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label>Role</label>
                                    <select class="form-control col-md-4" name="role">
                                        <option value="admin">Admin</option>
                                        <option value="manager">Manager</option>
                                        <option value="customer">Customer</option>
                                    </select>
                                </div>
                                <div class="d-flex justify-content-between">
                                    <div>
                                        <a class="btn btn-default" href="{{ route('user.index') }}">Back</a>
                                        <button type="button" class="btn btn-default" onclick="remove_function()">Reset
                                        </button>
                                    </div>
                                    <button type="submit" class="btn btn-primary">Save</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('scrip')
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script type="text/javascript">
        function remove_function() {
            $(".reset").attr('value', '');
        }

        const password = $('#password');
        const cf_password = $('#cf_password');
        const error_pass = $('#error_pass');

        function checkpass() {
            if (password.val() == cf_password.val()) {
                $("form").on('submit', function (e) {
                    return true;
                })
            } else {
                error_pass.append('</br><div class="alert alert-danger">\n' +
                    '  Re-entered password does not match\n' +
                    '</div>')
                $("form").on('submit', function (e) {
                    return false;
                })

            }
        }
    </script>
@endpush

resources/views/User/list.blade.php
@extends('layouts.main')
@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">User List</h3>
                    </div>
                    <div class="card-body">
                        <table id="example2" class="table table-bordered table-hover">
                            <thead>
                            <tr>
                                <th>No.</th>
                                <th>User Name</th>
                                <th>Email</th>
                                <th>DOB</th>
                                <th>Role</th>
                                <th>Action</th>
                                <th>Image</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach ($users as $key => $user)
                                <tr>
                                    <td>{{++$key}}</td>
                                    <td>{{$user->name}}</td>
                                    <td>{{$user->email}}</td>
                                    <td>{{\Carbon\Carbon::parse($user->dob)->format('d/m/Y')}}</td>
                                    <td>{{$user->role}}</td>
                                    <td>
                                        <img src="storage/".$user->image"></img>
                                    </td>
                                    <td>
                                        <a class="btn btn-success" href="{{ route('user.show', $user) }}"
                                           title="Edit"><i class="fa fa-eye"></i></a>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
    {{$users->links('Layout.pagelist')}}
@endsection